In [14]:
import pandas as pd
import os

In [15]:
data_pwd = "../datasets/adidas_tick_options.csv"

In [16]:
option_raw = pd.read_csv(data_pwd)
option_raw

,SecurityID,OptionID,Exchange,Currency,Bid,UnderlyingBid,Ask,UnderlyingAsk,Last,UnderlyingLast,...,ContractSize,OptionStyle,Version,ExerciseStyle,Expiration,StartDate,VALOR,Issuer,SEDOL,ISIN
0,500096,153742564,21,814,17.120001,77.750000,18.620001,77.750000,17.870001,77.750000,...,100,0,0,A,2013-04-19,2013-01-21,11730015,adidas AG,4031976,DE000A1EWWW0
1,500096,153703857,21,814,-99.989998,78.269997,-99.989998,78.269997,76.959999,78.269997,...,100,0,2,E,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
2,500096,153123500,21,814,-99.989998,78.900002,-99.989998,78.900002,1.510000,78.900002,...,100,0,2,E,2016-12-16,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
3,500096,153779773,21,814,-99.989998,76.199997,-99.989998,76.199997,20.950001,76.199997,...,100,0,2,E,2013-05-17,2013-02-18,11730015,adidas AG,4031976,DE000A1EWWW0
4,500096,153703810,21,814,-99.989998,71.639999,0.150000,71.639999,0.150000,71.639999,...,100,0,0,A,2013-03-15,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8691,500096,151977003,21,814,49.419998,77.750000,50.220001,77.750000,49.820000,77.750000,...,100,0,0,A,2014-12-19,2010-10-11,11730015,adidas AG,4031976,DE000A1EWWW0
8692,500096,153122332,21,814,0.600000,70.540001,0.750000,70.540001,0.675000,70.540001,...,100,0,0,A,2014-06-20,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8693,500096,153123161,21,814,-99.989998,79.750000,-99.989998,79.750000,4.920000,79.750000,...,100,0,2,E,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8694,500096,153547336,21,814,0.210000,78.889999,0.330000,78.889999,0.270000,78.889999,...,100,0,0,A,2013-09-20,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8695,500096,153800530,21,814,0.190000,78.889999,0.340000,78.889999,0.265000,78.889999,...,100,0,0,A,2014-06-20,2013-02-21,11730015,adidas AG,4031976,DE000A1EWWW0

In [17]:
#######################################
#### Create 2 dfs: Calls and Puts #####
#######################################

# Filter Only EUROPEAN STYLE Options - as we are comparing against Black-Scholes

option_raw_eu = option_raw[option_raw["ExerciseStyle"] == "E"]


# General Calls and Puts
call_df = option_raw[option_raw["CallPut"] == "C"] # Call DataFrame

put_df = option_raw[option_raw["CallPut"] == "P"] # Put DataFrame

# European Calls and Puts
call_eu_df = option_raw_eu[option_raw_eu["CallPut"] == "C"]
put_eu_df = option_raw_eu[option_raw_eu["CallPut"] == "P"]

save_dir = os.path.dirname(data_pwd)


# Paths to save the new DataFrames
call_save_path = os.path.join(save_dir, "call_options.csv")
put_save_path = os.path.join(save_dir, "put_options.csv")

put_eu_save_path = os.path.join(save_dir, "put_options_eu.csv")
call_eu_save_path = os.path.join(save_dir, "call_options_eu.csv")

# Save the DataFrames as CSV
call_df.to_csv(call_save_path, index=False)
put_df.to_csv(put_save_path, index=False)

call_eu_df.to_csv(call_eu_save_path, index=False)
put_eu_df.to_csv(put_eu_save_path, index=False)


print(f"Call DataFrame saved at: {call_save_path}")
print(f"Put DataFrame saved at: {put_save_path}")
print(f"Call DataFrame saved at: {call_eu_save_path}")
print(f"Put DataFrame saved at: {put_eu_save_path}")

Call DataFrame saved at: ../datasets\call_options.csv
Put DataFrame saved at: ../datasets\put_options.csv
Call DataFrame saved at: ../datasets\call_options_eu.csv
Put DataFrame saved at: ../datasets\put_options_eu.csv

In [18]:
call_df

,SecurityID,OptionID,Exchange,Currency,Bid,UnderlyingBid,Ask,UnderlyingAsk,Last,UnderlyingLast,...,ContractSize,OptionStyle,Version,ExerciseStyle,Expiration,StartDate,VALOR,Issuer,SEDOL,ISIN
0,500096,153742564,21,814,17.120001,77.750000,18.620001,77.750000,17.870001,77.750000,...,100,0,0,A,2013-04-19,2013-01-21,11730015,adidas AG,4031976,DE000A1EWWW0
1,500096,153703857,21,814,-99.989998,78.269997,-99.989998,78.269997,76.959999,78.269997,...,100,0,2,E,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
3,500096,153779773,21,814,-99.989998,76.199997,-99.989998,76.199997,20.950001,76.199997,...,100,0,2,E,2013-05-17,2013-02-18,11730015,adidas AG,4031976,DE000A1EWWW0
5,500096,153123207,21,814,-99.989998,76.379997,-99.989998,76.379997,12.230000,76.379997,...,100,0,2,E,2014-12-19,2012-04-30,11730015,adidas AG,4031976,DE000A1EWWW0
10,500096,153779820,21,814,3.480000,79.750000,3.640000,79.750000,3.560000,79.750000,...,100,0,0,A,2013-05-17,2013-02-18,11730015,adidas AG,4031976,DE000A1EWWW0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8685,500096,151976957,21,814,-99.989998,76.379997,-99.989998,76.379997,48.389999,76.379997,...,100,0,0,A,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8687,500096,151976959,21,814,39.299999,71.639999,40.509998,71.639999,39.904999,71.639999,...,100,0,0,A,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8691,500096,151977003,21,814,49.419998,77.750000,50.220001,77.750000,49.820000,77.750000,...,100,0,0,A,2014-12-19,2010-10-11,11730015,adidas AG,4031976,DE000A1EWWW0
8693,500096,153123161,21,814,-99.989998,79.750000,-99.989998,79.750000,4.920000,79.750000,...,100,0,2,E,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8695,500096,153800530,21,814,0.190000,78.889999,0.340000,78.889999,0.265000,78.889999,...,100,0,0,A,2014-06-20,2013-02-21,11730015,adidas AG,4031976,DE000A1EWWW0

In [19]:
put_df

,SecurityID,OptionID,Exchange,Currency,Bid,UnderlyingBid,Ask,UnderlyingAsk,Last,UnderlyingLast,...,ContractSize,OptionStyle,Version,ExerciseStyle,Expiration,StartDate,VALOR,Issuer,SEDOL,ISIN
2,500096,153123500,21,814,-99.989998,78.900002,-99.989998,78.900002,1.510,78.900002,...,100,0,2,E,2016-12-16,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
4,500096,153703810,21,814,-99.989998,71.639999,0.150000,71.639999,0.150,71.639999,...,100,0,0,A,2013-03-15,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
6,500096,153703903,21,814,-99.989998,70.279999,-99.989998,70.279999,28.600,70.279999,...,100,0,2,E,2017-12-15,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
7,500096,153122945,21,814,-99.989998,76.199997,-99.989998,76.199997,0.020,76.199997,...,100,0,0,A,2013-03-15,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8,500096,153742611,21,814,-99.989998,70.540001,-99.989998,70.540001,11.550,70.540001,...,100,0,2,E,2013-04-19,2013-01-21,11730015,adidas AG,4031976,DE000A1EWWW0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,500096,151976962,21,814,-99.989998,71.669998,0.150000,71.669998,0.150,71.669998,...,100,0,0,A,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8689,500096,151976968,21,814,0.010000,76.199997,0.100000,76.199997,0.055,76.199997,...,100,0,0,A,2013-06-21,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8690,500096,151976980,21,814,-99.989998,78.900002,0.140000,78.900002,0.140,78.900002,...,100,0,0,A,2013-12-20,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8692,500096,153122332,21,814,0.600000,70.540001,0.750000,70.540001,0.675,70.540001,...,100,0,0,A,2014-06-20,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0
8694,500096,153547336,21,814,0.210000,78.889999,0.330000,78.889999,0.270,78.889999,...,100,0,0,A,2013-09-20,2013-01-02,11730015,adidas AG,4031976,DE000A1EWWW0